# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: kanywst.y509
PackageVersion: 1.6.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: y509.exe
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kanywst/y509/releases/download/v1.6.0/y509-1.6.0-windows-amd64.zip
  InstallerSha256: 97D0C42878395F6234B623D80EFC095371D4473E89BE647E289B103BBA0B4D59
- Architecture: arm64
  InstallerUrl: https://github.com/kanywst/y509/releases/download/v1.6.0/y509-1.6.0-windows-arm64.zip
  InstallerSha256: 42170DB592002B252AAA90EC0A4BBA97C599B4DF0B33FA28676587DF7A5F5191
ManifestType: installer
ManifestVersion: 1.12.0
