# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: kanywst.y509
PackageVersion: 1.11.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: y509.exe
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kanywst/y509/releases/download/v1.11.0/y509-1.11.0-windows-amd64.zip
  InstallerSha256: 80AD81F9780FB5E41DFE78A204B74DC9C37B4BA415CECE3FCF463C8D1A568F9F
- Architecture: arm64
  InstallerUrl: https://github.com/kanywst/y509/releases/download/v1.11.0/y509-1.11.0-windows-arm64.zip
  InstallerSha256: 5E8BD7F1C400F1336C8A9B38A392A1BF7001AB04E2F48269C2DCA5936B422697
ManifestType: installer
ManifestVersion: 1.12.0
